export function generateCardioReportHTML({ readings, unit }) {
  return `
    <html>
      <head>
        <style>
          body {
            font-family: Helvetica, sans-serif;
            padding: 20px;
            color: #1e293b;
          }

          h1 {
            color: #e11d48;
            text-align: center;
            margin-bottom: 30px;
          }

          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
          }

          th, td {
            border: 1px solid #e2e8f0;
            padding: 12px;
            text-align: left;
          }

          th {
            background-color: #f8fafc;
            font-weight: bold;
          }

          .summary {
            background: #fff1f2;
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 20px;
          }

          .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 12px;
            color: #64748b;
          }
        </style>
      </head>

      <body>
        <h1>CardioLog Report</h1>

        <div class="summary">
          <p><strong>Total Readings:</strong> ${readings.length}</p>
          <p><strong>Pressure Unit:</strong> ${unit}</p>
          <p><strong>Generated on:</strong> ${new Date().toLocaleString()}</p>
        </div>

        <table>
          <thead>
            <tr>
              <th>Date</th>
              <th>Systolic (${unit})</th>
              <th>Diastolic (${unit})</th>
              <th>Pulse (bpm)</th>
            </tr>
          </thead>
          <tbody>
            ${readings
              .map((r) => {
                const systolic =
                  unit === "kPa" ? (r.systolic / 7.5).toFixed(1) : r.systolic;

                const diastolic =
                  unit === "kPa" ? (r.diastolic / 7.5).toFixed(1) : r.diastolic;

                return `
                  <tr>
                    <td>${new Date(
                      r.createdAt || r.timestamp
                    ).toLocaleDateString()}</td>
                    <td>${systolic}</td>
                    <td>${diastolic}</td>
                    <td>${r.pulse || "-"}</td>
                  </tr>
                `;
              })
              .join("")}
          </tbody>
        </table>

        <div class="footer">
          Generated by CardioLog App
        </div>
      </body>
    </html>
  `;
}
